name: Deploy Changed Functions

on:
  push:
    branches: [main]

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Allows comparing with the previous commit

      - name: Check Changes
        run: |
          git diff --name-only HEAD^ HEAD
